INPUT_FILE = "e4.cdd"
ERROR_FILE = "e4.txt"
UNIX_CLEAN_COMMAND = ["grep", "-v", "#", INPUT_FILE]
WIN_CLEAN_COMMAND = ["findstr", "/v", "#", INPUT_FILE]
CHAR_COLOR = 'red'
SYS_ID = 'query acc.'
SYS_LEN = 'query length'
DOM_ID = 'subject accs.'
DOM_START = 'q. start'
DOM_END = 'q. end'